// Curated riddles + lateral-thinking puzzles. Vetted, single clear answer.
// `keys` = words that must appear in a guess to count it right (lowercased,
// punctuation-stripped). `a` is the canonical answer shown on reveal.

export interface Riddle {
  q: string;
  a: string;
  keys: string[][]; // guess passes if it contains every word of ANY inner group
  hint?: string;
}

export const RIDDLES: Riddle[] = [
  { q: "The more of me you take, the more you leave behind. What am I?", a: "Footsteps.", keys: [["footstep"], ["footprint"], ["steps"]] },
  { q: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", a: "An echo.", keys: [["echo"]] },
  { q: "I have keys but no locks, space but no room, and you can enter but can't go outside. What am I?", a: "A keyboard.", keys: [["keyboard"], ["key", "board"]] },
  { q: "What has to be broken before you can use it?", a: "An egg.", keys: [["egg"]] },
  { q: "What has hands but cannot clap?", a: "A clock.", keys: [["clock"], ["watch"]] },
  { q: "The person who makes it has no need of it. The person who buys it has no use for it. The person who uses it can neither see nor feel it. What is it?", a: "A coffin.", keys: [["coffin"], ["casket"]] },
  { q: "What gets wetter the more it dries?", a: "A towel.", keys: [["towel"]] },
  { q: "I'm tall when I'm young, and short when I'm old. What am I?", a: "A candle.", keys: [["candle"], ["pencil"]] },
  { q: "What can travel around the world while staying in one corner?", a: "A stamp.", keys: [["stamp"]] },
  { q: "What has a head and a tail but no body?", a: "A coin.", keys: [["coin"], ["penny"]] },
  { q: "What has many needles but doesn't sew?", a: "A pine tree.", keys: [["pine"], ["christmas tree"], ["fir"], ["evergreen"]] },
  { q: "What has one eye but cannot see?", a: "A needle.", keys: [["needle"], ["hurricane"], ["storm"]] },
  { q: "What runs but never walks, has a mouth but never talks, has a bed but never sleeps?", a: "A river.", keys: [["river"], ["stream"]] },
  { q: "What comes down but never goes up?", a: "Rain.", keys: [["rain"]] },
  { q: "What can you catch but not throw?", a: "A cold.", keys: [["cold"], ["a cold"]] },
  { q: "What has a neck but no head?", a: "A bottle.", keys: [["bottle"], ["shirt"]] },
  { q: "What has words but never speaks?", a: "A book.", keys: [["book"]] },
  { q: "What has a thumb and four fingers but is not alive?", a: "A glove.", keys: [["glove"]] },
  { q: "What building has the most stories?", a: "A library.", keys: [["library"]] },
  { q: "What goes up and down but never moves?", a: "A staircase.", keys: [["stair"], ["staircase"], ["steps"], ["temperature"]] },
  { q: "Forward I am heavy, but backward I am not. What am I?", a: "The word \"ton\".", keys: [["ton"]], hint: "It's a word." },
  { q: "What five-letter word becomes shorter when you add two letters to it?", a: "Short (→ shorter).", keys: [["short"]] },
  { q: "What word is spelled incorrectly in every dictionary?", a: "\"Incorrectly.\"", keys: [["incorrectly"]] },
  { q: "What has 13 hearts but no other organs?", a: "A deck of cards.", keys: [["deck of cards"], ["cards"], ["playing cards"]] },
  { q: "If you have me, you want to share me. If you share me, you no longer have me. What am I?", a: "A secret.", keys: [["secret"]] },
  { q: "What can fill a room but takes up no space?", a: "Light.", keys: [["light"], ["sound"], ["air"]] },
  { q: "I have branches, but no fruit, trunk, or leaves. What am I?", a: "A bank.", keys: [["bank"]] },
  { q: "What is always in front of you but can't be seen?", a: "The future.", keys: [["future"]] },
  { q: "What breaks yet never falls, and what falls yet never breaks?", a: "Day breaks and night falls.", keys: [["day", "night"], ["dawn", "night"]] },
  { q: "A man describes his daughters: \"They are all blonde but two, all brunette but two, and all redheaded but two.\" How many daughters does he have?", a: "Three — one of each.", keys: [["three"], ["3"]] },
  { q: "What has a bark but no bite?", a: "A tree.", keys: [["tree"]] },
  { q: "You see a boat filled with people, yet there isn't a single person on board. How?", a: "Everyone on board is married.", keys: [["married"]], hint: "\"Single.\"" },
  { q: "What can't talk but will reply when spoken to?", a: "An echo.", keys: [["echo"]] },
  { q: "What has four wheels and flies?", a: "A garbage truck.", keys: [["garbage truck"], ["trash truck"], ["bin lorry"], ["dumpster"]] },
  { q: "The more you take away from me, the bigger I get. What am I?", a: "A hole.", keys: [["hole"], ["pit"], ["debt"]] },
  { q: "I go all around the world but never leave the corner. What am I?", a: "A stamp.", keys: [["stamp"]] },
  { q: "What kind of coat is best put on wet?", a: "A coat of paint.", keys: [["paint"]] },
  { q: "What has an eye but cannot see, and helps you make a shirt?", a: "A needle.", keys: [["needle"]] },
  { q: "Two fathers and two sons go fishing. Each catches one fish, yet only three fish are caught. How?", a: "They are a grandfather, a father, and a son.", keys: [["grandfather"], ["grandpa"], ["three generations"]] },
  { q: "What has to be given before it can be kept?", a: "A promise. (Also accepted: your word.)", keys: [["promise"], ["word"]] },
  { q: "What can you hold in your left hand but never in your right?", a: "Your right elbow.", keys: [["elbow"], ["right hand"], ["right arm"]] },
  { q: "What is so fragile that saying its name breaks it?", a: "Silence.", keys: [["silence"]] },
  { q: "A woman shoots her husband, holds him under water for five minutes, then hangs him. Ten minutes later they go out to dinner together. How?", a: "She's a photographer — she shot a photo, developed it, and hung it to dry.", keys: [["photo"], ["photograph"], ["picture"], ["camera"]] },
  { q: "What gets bigger the more you take from it, and there is nothing left when it's done?", a: "A hole (or a debt being paid).", keys: [["hole"], ["debt"]] },
  { q: "What invention lets you look right through a wall?", a: "A window.", keys: [["window"]] },

  { q: "What has legs but doesn't walk?", a: "A table (or chair).", keys: [["table"], ["chair"], ["stool"]] },
  { q: "What can you break, even if you never pick it up or touch it?", a: "A promise.", keys: [["promise"], ["silence"]] },
  { q: "What has a bottom at the top?", a: "Your legs.", keys: [["legs"]] },
  { q: "What kind of tree can you carry in your hand?", a: "A palm.", keys: [["palm"]] },
  { q: "What has a ring but no finger?", a: "A telephone (or a bell).", keys: [["telephone"], ["phone"], ["bell"]] },
  { q: "What has cities but no houses, forests but no trees, and water but no fish?", a: "A map.", keys: [["map"]] },
  { q: "What has a face and two hands but no arms or legs?", a: "A clock.", keys: [["clock"], ["watch"]] },
  { q: "What has teeth but cannot bite?", a: "A comb (also: a saw, a zipper, a gear).", keys: [["comb"], ["saw"], ["zipper"], ["gear"]] },
  { q: "What can run but never walks, and murmurs but never talks?", a: "A river (or a brook).", keys: [["river"], ["brook"], ["stream"], ["creek"]] },
  { q: "What has roots that nobody sees, and is taller than trees; up, up it goes, and yet it never grows?", a: "A mountain.", keys: [["mountain"]] },
  { q: "Voiceless it cries, wingless it flutters, toothless it bites, mouthless it mutters. What is it?", a: "The wind.", keys: [["wind"]] },
  { q: "This thing all things devours: birds, beasts, trees, flowers; gnaws iron, bites steel, grinds hard stones to meal. What is it?", a: "Time.", keys: [["time"]] },
  { q: "It cannot be seen, cannot be felt, cannot be heard, cannot be smelt. It lies behind stars and under hills, and empty holes it fills. What is it?", a: "Darkness.", keys: [["dark"], ["darkness"]] },
  { q: "Alive without breath, as cold as death; never thirsty, ever drinking, all in mail never clinking. What is it?", a: "A fish.", keys: [["fish"]] },
  { q: "What runs around a house but never moves?", a: "A fence (or a wall).", keys: [["fence"], ["wall"]] },
  { q: "What has a spine but no bones?", a: "A book.", keys: [["book"]] },
  { q: "What kind of room has no doors or windows?", a: "A mushroom.", keys: [["mushroom"]] },
  { q: "What has four legs in the morning, two at noon, and three in the evening?", a: "A human (Riddle of the Sphinx — crawling, walking, then with a cane).", keys: [["human"], ["man"], ["person"], ["people"]], hint: "Think of a lifetime as one day." },
  { q: "What gets sharper the more you use it?", a: "Your brain (or your mind).", keys: [["brain"], ["mind"], ["memory"]] },
  { q: "What can you keep after giving it to someone?", a: "Your word (a promise).", keys: [["word"], ["promise"]] },
  { q: "The more it dries, the wetter it gets. What is it?", a: "A towel.", keys: [["towel"]] },
  { q: "What five-letter word sounds the same after you remove four of its letters?", a: "\"Queue.\"", keys: [["queue"]] },
  { q: "What word contains 26 letters but only three syllables?", a: "\"Alphabet.\"", keys: [["alphabet"]] },
  { q: "What English word has three consecutive double letters?", a: "\"Bookkeeper\" (oo-kk-ee).", keys: [["bookkeeper"]] },
  { q: "What begins with T, ends with T, and has T in it?", a: "A teapot.", keys: [["teapot"], ["tea pot"]] },
  { q: "What occurs once in a minute, twice in a moment, and never in a thousand years?", a: "The letter M.", keys: [["m"], ["letter m"]] },
  { q: "What comes once in a year, twice in a week, but never in a day?", a: "The letter E.", keys: [["e"], ["letter e"]] },
  { q: "I am the beginning of the end, the end of every place. I am the start of eternity, the end of time and space. What am I?", a: "The letter E.", keys: [["e"], ["letter e"]] },
  { q: "What three positive numbers give the same result when multiplied together as when added together?", a: "1, 2, and 3.", keys: [["1", "2", "3"], ["one", "two", "three"]] },
  { q: "A farmer has 17 sheep and all but 9 die. How many are left?", a: "Nine.", keys: [["9"], ["nine"]] },
  { q: "If it takes 5 machines 5 minutes to make 5 widgets, how long for 100 machines to make 100 widgets?", a: "5 minutes.", keys: [["5 minute"], ["five minute"], ["5 min"]] },
  { q: "How many months have 28 days?", a: "All 12 of them.", keys: [["all"], ["12"], ["twelve"], ["every"]] },
  { q: "A doctor gives you three pills and says to take one every half hour. How long do the pills last?", a: "One hour.", keys: [["1 hour"], ["one hour"], ["an hour"], ["60 minute"]] },
  { q: "Two coins add up to 30 cents, and one of them is not a nickel. What are they?", a: "A quarter and a nickel — the quarter is the one that's not a nickel.", keys: [["quarter", "nickel"]] },
  { q: "A man builds a house with all four sides facing south. A bear walks by. What color is the bear?", a: "White — the house is at the North Pole, so it's a polar bear.", keys: [["white"], ["polar"]] },
  { q: "What can you put in a bucket to make it weigh less?", a: "A hole.", keys: [["hole"]] },
  { q: "Forward I'm heavy; backward I'm not. What word am I?", a: "\"Ton.\"", keys: [["ton"]] },
  { q: "What's full of holes but still holds water?", a: "A sponge.", keys: [["sponge"]] },
  { q: "What goes through towns and over hills but never moves?", a: "A road.", keys: [["road"], ["path"], ["highway"]] },
  { q: "What can you serve but never eat?", a: "A tennis ball (or a volleyball) — you serve it.", keys: [["tennis"], ["volleyball"], ["ball"], ["subpoena"]] },
  { q: "What has 88 keys but can't open a single door?", a: "A piano.", keys: [["piano"]] },
  { q: "What has a heart that doesn't beat?", a: "An artichoke (or a deck of cards).", keys: [["artichoke"], ["cards"]] },
  { q: "What two things can you never eat for breakfast?", a: "Lunch and dinner.", keys: [["lunch", "dinner"], ["lunch", "supper"]] },
  { q: "What gets broken without being held?", a: "A promise.", keys: [["promise"]] },
  { q: "I fly without wings, I cry without eyes. Wherever I go, darkness follows me. What am I?", a: "A cloud.", keys: [["cloud"]] },
  { q: "You can hold me in your right hand but never in your left. What am I?", a: "Your left hand.", keys: [["left hand"], ["left arm"]] },
  { q: "What has a golden head and a golden tail but no golden body?", a: "A gold coin.", keys: [["coin"], ["penny"], ["dime"]] },
  { q: "What always goes to bed with its shoes on?", a: "A horse.", keys: [["horse"]] },
  { q: "What has one head, one foot, and four legs?", a: "A bed.", keys: [["bed"]] },
  { q: "What has 21 eyes but cannot see?", a: "A die (a single die has 21 pips).", keys: [["die"], ["dice"]] },
  { q: "What kind of band never plays music?", a: "A rubber band.", keys: [["rubber band"], ["rubber"], ["wedding band"], ["hair band"]] },
  { q: "What has a thousand needles but isn't a pincushion?", a: "A porcupine (or a cactus).", keys: [["porcupine"], ["cactus"], ["hedgehog"]] },
  { q: "What can point in every direction but can't reach the destination by itself?", a: "A signpost (or a compass needle).", keys: [["signpost"], ["sign post"], ["compass"], ["arrow"]] },
  { q: "What kind of key opens a banana?", a: "A monkey.", keys: [["monkey"]] },
  { q: "What kind of dog keeps the best time?", a: "A watchdog.", keys: [["watchdog"], ["watch dog"]] },
  { q: "What has ears but cannot hear?", a: "A cornfield (an ear of corn).", keys: [["corn"], ["cornfield"], ["wheat"]] },
  { q: "What can be cracked, made, told, and played?", a: "A joke.", keys: [["joke"]] },
  { q: "What has a bank but no money?", a: "A river.", keys: [["river"]] },
  { q: "What flies when it's born, lies while it's alive, and runs when it's dead?", a: "A snowflake.", keys: [["snowflake"], ["snow"]] },
  { q: "What comes in through one, out through the other, and connects them yet holds nothing?", a: "A tunnel.", keys: [["tunnel"]] },
  { q: "The more you have of it, the less you see. What is it?", a: "Darkness (or fog).", keys: [["dark"], ["darkness"], ["fog"]] },
  { q: "A cowboy rides into town on Friday, stays three days, and rides out on Friday. How?", a: "His horse is named Friday.", keys: [["horse"], ["named friday"], ["horse's name"], ["horse is friday"]] },
  { q: "What can you catch but not throw, and everyone eventually gets?", a: "A cold.", keys: [["cold"]] },
  { q: "I have a mouth but never eat, a bed but never sleep. What am I?", a: "A river.", keys: [["river"]] },
  { q: "What tastes better than it smells?", a: "A tongue.", keys: [["tongue"]] },
  { q: "What has a neck and no head, two arms and no hands?", a: "A shirt (or a sweater).", keys: [["shirt"], ["sweater"], ["jacket"], ["coat"]] },
  { q: "What building has thousands of stories but no elevators are needed to read them?", a: "A library.", keys: [["library"]] },
  { q: "What can you hold without ever touching it?", a: "A conversation (or your breath).", keys: [["conversation"], ["breath"], ["grudge"]] },
  { q: "What has hands and a face but no arms, legs, or eyes?", a: "A clock.", keys: [["clock"], ["watch"]] },
  { q: "What kind of coat has no buttons, no zipper, and is always wet when you put it on?", a: "A coat of paint.", keys: [["paint"]] },
  { q: "I have branches but no leaves, no trunk, and no fruit. What am I?", a: "A bank (or a library, or a river).", keys: [["bank"], ["library"], ["river"]] },
  { q: "What is easy to get into but hard to get out of?", a: "Trouble.", keys: [["trouble"], ["debt"]] },
  { q: "What is always coming but never arrives?", a: "Tomorrow.", keys: [["tomorrow"]] },
  { q: "What word is always pronounced wrong?", a: "\"Wrong.\"", keys: [["wrong"]] },
  { q: "What starts and ends with 'e' but usually contains only one letter?", a: "An envelope.", keys: [["envelope"]] },
  { q: "If two's company and three's a crowd, what are four and five?", a: "Nine.", keys: [["9"], ["nine"]] },
  { q: "What has one voice but goes on four feet in the morning, two at midday, and three in the evening?", a: "A person, over a lifetime.", keys: [["person"], ["human"], ["man"], ["people"]] },
  { q: "A boy and a doctor are fishing. The boy is the doctor's son, but the doctor is not the boy's father. Who is the doctor?", a: "His mother.", keys: [["mother"], ["mom"], ["mum"]] },
  { q: "I turn once, what is out will not get in. I turn again, what is in will not get out. What am I?", a: "A key.", keys: [["key"]] },
  { q: "What five-letter word has six left when you take two letters away?", a: "\"Sixty.\"", keys: [["sixty"]] },
  { q: "What common word starts with 'IS', ends with 'AND', and has 'LA' in the middle?", a: "\"Island.\"", keys: [["island"]] },
  { q: "What can go up a chimney down, but can't go down a chimney up?", a: "An umbrella.", keys: [["umbrella"]] },
  { q: "What English word retains the same pronunciation even after four of its five letters are removed?", a: "\"Queue.\"", keys: [["queue"]] },
  { q: "Take away my first letter and I sound the same. Take away my last letter and I still sound the same. Even my middle letter can go. What word am I?", a: "\"Empty\" (M-T).", keys: [["empty"]] },
  { q: "A man is found dead in a field with an unopened package beside him. What was in the package?", a: "A parachute that failed to open.", keys: [["parachute"]] },
  { q: "There are two ropes, each burns in exactly one hour but not evenly. How do you measure 45 minutes?", a: "Light one rope at both ends and the other at one end; when the first burns out (30 min) light the second end of the other — it finishes 15 min later.", keys: [["both ends"], ["light both"]], hint: "You can light either end." },
  { q: "What has 4 fingers and a thumb but isn't alive?", a: "A glove.", keys: [["glove"]] },
  { q: "What gets wetter as it dries you?", a: "A towel.", keys: [["towel"]] },
  { q: "What loses its head in the morning and gets it back at night?", a: "A pillow.", keys: [["pillow"]] },
  { q: "Where does today come before yesterday?", a: "In the dictionary.", keys: [["dictionary"]] },
  { q: "What can travel the world while staying in one spot?", a: "A stamp.", keys: [["stamp"]] },
  { q: "What breaks on the water but never on land?", a: "A wave.", keys: [["wave"]] },
  { q: "What is put on a table, cut, and passed around, but never eaten?", a: "A deck of cards.", keys: [["cards"], ["deck of cards"]] },
  { q: "What runs but has no legs, and roars but has no mouth?", a: "An engine (or a waterfall).", keys: [["engine"], ["motor"], ["waterfall"]] },
  { q: "What has millions of teeth but never brushes them?", a: "A saw (or a zipper, or a mountain range).", keys: [["saw"], ["zipper"], ["mountain"]] },
  { q: "What has a thumb and fingers but isn't a hand?", a: "A glove.", keys: [["glove"]] },
  { q: "What lives when it eats and dies when it drinks?", a: "Fire.", keys: [["fire"]] },
  { q: "What goes up when the rain comes down?", a: "An umbrella.", keys: [["umbrella"]] },
  { q: "The more you feed it, the taller it grows; give it a drink and it dies. What is it?", a: "Fire.", keys: [["fire"]] },
  { q: "What has a head, a tail, is brown, and has no legs?", a: "A penny.", keys: [["penny"], ["coin"]] },
  { q: "What has 10 letters and starts with gas?", a: "Automobile.", keys: [["automobile"]] },
  { q: "What can you find at the end of a rainbow?", a: "The letter W.", keys: [["w"], ["letter w"], ["pot of gold"]] },
];
