// Latin / Greek roots for the etymology drill. `english` = a few clean, real
// derivatives (used for the accepted answers and the reveal). Keep glosses to a
// single comma-separated sense group — no semicolons.

export interface Root {
  root: string;
  lang: 'Latin' | 'Greek' | 'Greek/Latin';
  gloss: string;
  english: string[];
}

export const ROOTS: Root[] = [
  // ── Latin: verbs of motion / carrying / sending ──────────────────────
  { root: 'ferō / ferre / lāt', lang: 'Latin', gloss: 'to carry, bear', english: ['transfer', 'refer', 'defer', 'infer', 'fertile', 'confer', 'relate', 'translate'] },
  { root: 'port', lang: 'Latin', gloss: 'to carry', english: ['portable', 'transport', 'import', 'export', 'porter', 'report', 'deport'] },
  { root: 'mit / miss', lang: 'Latin', gloss: 'to send, let go', english: ['transmit', 'mission', 'dismiss', 'permit', 'submit', 'missile', 'emit'] },
  { root: 'duc / duct', lang: 'Latin', gloss: 'to lead', english: ['conduct', 'produce', 'reduce', 'aqueduct', 'induce', 'educate', 'abduct'] },
  { root: 'ven / vent', lang: 'Latin', gloss: 'to come', english: ['convene', 'event', 'invent', 'prevent', 'venue', 'intervene', 'avenue'] },
  { root: 'ced / cess', lang: 'Latin', gloss: 'to go, yield', english: ['proceed', 'recede', 'access', 'concede', 'precedent', 'successor', 'excess'] },
  { root: 'grad / gress', lang: 'Latin', gloss: 'to step, go', english: ['gradual', 'progress', 'regress', 'digress', 'aggressive', 'grade', 'ingredient'] },
  { root: 'curr / curs', lang: 'Latin', gloss: 'to run', english: ['current', 'cursor', 'recur', 'excursion', 'concur', 'cursive', 'precursor'] },
  { root: 'sequ / secut', lang: 'Latin', gloss: 'to follow', english: ['sequence', 'consequence', 'sequel', 'consecutive', 'subsequent', 'pursue'] },
  { root: 'trah / tract', lang: 'Latin', gloss: 'to pull, draw', english: ['tractor', 'attract', 'extract', 'contract', 'subtract', 'distract', 'retract'] },
  { root: 'pel / puls', lang: 'Latin', gloss: 'to drive, push', english: ['propel', 'expel', 'compel', 'repel', 'pulse', 'impulse', 'compulsory'] },
  { root: 'flu / flux', lang: 'Latin', gloss: 'to flow', english: ['fluid', 'influence', 'fluent', 'flux', 'affluent', 'confluence', 'influenza'] },
  { root: 'volv / volut', lang: 'Latin', gloss: 'to roll, turn', english: ['revolve', 'evolve', 'involve', 'revolution', 'evolution', 'convoluted'] },
  { root: 'vert / vers', lang: 'Latin', gloss: 'to turn', english: ['convert', 'reverse', 'divert', 'version', 'introvert', 'universe', 'adverse'] },
  { root: 'jac / ject', lang: 'Latin', gloss: 'to throw', english: ['reject', 'inject', 'project', 'eject', 'object', 'trajectory', 'adjacent'] },
  { root: 'lāb / laps', lang: 'Latin', gloss: 'to slip, slide', english: ['collapse', 'elapse', 'relapse', 'lapse', 'prolapse'] },

  // ── Latin: speaking / writing / seeing / hearing ────────────────────
  { root: 'dic / dict', lang: 'Latin', gloss: 'to say, speak', english: ['dictate', 'predict', 'contradict', 'diction', 'verdict', 'edict', 'dictionary'] },
  { root: 'loqu / locu', lang: 'Latin', gloss: 'to speak', english: ['eloquent', 'loquacious', 'soliloquy', 'elocution', 'circumlocution', 'colloquial'] },
  { root: 'voc / vok', lang: 'Latin', gloss: 'to call, voice', english: ['vocal', 'invoke', 'revoke', 'provoke', 'advocate', 'vocation', 'evoke'] },
  { root: 'nunc / nounc', lang: 'Latin', gloss: 'to report, announce', english: ['announce', 'pronounce', 'denounce', 'renounce', 'enunciate'] },
  { root: 'scrib / script', lang: 'Latin', gloss: 'to write', english: ['scribe', 'describe', 'manuscript', 'inscription', 'prescribe', 'transcript', 'scripture'] },
  { root: 'leg / lect', lang: 'Latin', gloss: 'to read, choose, gather', english: ['legible', 'lecture', 'collect', 'select', 'elect', 'intellect', 'legend'] },
  { root: 'spec / spect', lang: 'Latin', gloss: 'to look, watch', english: ['spectator', 'inspect', 'perspective', 'spectacle', 'suspect', 'respect', 'prospect'] },
  { root: 'vid / vis', lang: 'Latin', gloss: 'to see', english: ['video', 'vision', 'evident', 'visible', 'provide', 'supervise', 'envisage'] },
  { root: 'aud / audit', lang: 'Latin', gloss: 'to hear', english: ['audience', 'audio', 'auditorium', 'audible', 'audition', 'auditor'] },
  { root: 'sent / sens', lang: 'Latin', gloss: 'to feel, perceive', english: ['sentiment', 'sensory', 'consent', 'resent', 'sensation', 'dissent', 'sentinel'] },
  { root: 'mon / monit', lang: 'Latin', gloss: 'to warn, advise', english: ['monitor', 'admonish', 'premonition', 'monument', 'summon'] },

  // ── Latin: making / holding / doing ────────────────────────────────
  { root: 'fac / fect / fic', lang: 'Latin', gloss: 'to make, do', english: ['factory', 'manufacture', 'perfect', 'effect', 'fiction', 'efficient', 'defect'] },
  { root: 'cap / cept / cip', lang: 'Latin', gloss: 'to take, seize', english: ['capture', 'accept', 'concept', 'intercept', 'receive', 'capable', 'recipient'] },
  { root: 'ten / tent / tain', lang: 'Latin', gloss: 'to hold', english: ['tenant', 'retain', 'contain', 'maintain', 'tenacious', 'detain', 'content'] },
  { root: 'pon / pos / posit', lang: 'Latin', gloss: 'to place, put', english: ['component', 'compose', 'deposit', 'position', 'expose', 'postpone', 'opponent'] },
  { root: 'tend / tens / tent', lang: 'Latin', gloss: 'to stretch', english: ['extend', 'tension', 'intense', 'tendon', 'pretend', 'attend', 'distend'] },
  { root: 'frang / fract / frag', lang: 'Latin', gloss: 'to break', english: ['fracture', 'fragment', 'fragile', 'fraction', 'infringe', 'refract'] },
  { root: 'rump / rupt', lang: 'Latin', gloss: 'to break, burst', english: ['rupture', 'interrupt', 'erupt', 'corrupt', 'abrupt', 'bankrupt', 'disrupt'] },
  { root: 'string / strict', lang: 'Latin', gloss: 'to bind, draw tight', english: ['strict', 'restrict', 'constrict', 'stringent', 'constrain'] },
  { root: 'plic / plex / ply', lang: 'Latin', gloss: 'to fold', english: ['complicate', 'duplicate', 'complex', 'imply', 'replica', 'application', 'perplex'] },
  { root: 'grat', lang: 'Latin', gloss: 'pleasing, thankful', english: ['gratitude', 'grateful', 'gratify', 'ingrate', 'congratulate', 'gratuity'] },
  { root: 'reg / rect', lang: 'Latin', gloss: 'to rule, guide, keep straight', english: ['regal', 'regent', 'direct', 'correct', 'rectangle', 'regime', 'rectify'] },
  { root: 'sist / sta / stat', lang: 'Latin', gloss: 'to stand, set', english: ['insist', 'resist', 'stable', 'status', 'station', 'constant', 'stationary'] },
  { root: 'sed / sess / sid', lang: 'Latin', gloss: 'to sit, settle', english: ['sediment', 'session', 'reside', 'preside', 'subside', 'sedentary', 'obsess'] },

  // ── Latin: life / death / mind / body ─────────────────────────────
  { root: 'viv / vit', lang: 'Latin', gloss: 'life, to live', english: ['survive', 'revive', 'vivid', 'vital', 'vitamin', 'convivial', 'vivacious'] },
  { root: 'mort', lang: 'Latin', gloss: 'death', english: ['mortal', 'immortal', 'mortuary', 'mortician', 'mortgage', 'moribund'] },
  { root: 'nat / nasc', lang: 'Latin', gloss: 'to be born', english: ['native', 'nation', 'nature', 'innate', 'prenatal', 'nascent', 'renaissance'] },
  { root: 'anim', lang: 'Latin', gloss: 'life, breath, mind', english: ['animal', 'animate', 'unanimous', 'magnanimous', 'equanimity'] },
  { root: 'ment', lang: 'Latin', gloss: 'mind', english: ['mental', 'mention', 'comment', 'demented', 'reminisce'] },
  { root: 'cor / cord / card', lang: 'Latin', gloss: 'heart', english: ['cordial', 'accord', 'discord', 'courage', 'record', 'concord'] },
  { root: 'corp / corpor', lang: 'Latin', gloss: 'body', english: ['corporal', 'corpse', 'corporation', 'incorporate', 'corps', 'corpulent'] },
  { root: 'capit / capt', lang: 'Latin', gloss: 'head', english: ['capital', 'captain', 'decapitate', 'per capita', 'recapitulate'] },
  { root: 'ped', lang: 'Latin', gloss: 'foot', english: ['pedal', 'pedestrian', 'pedestal', 'biped', 'impede', 'expedite', 'pedigree'] },
  { root: 'manus', lang: 'Latin', gloss: 'hand', english: ['manual', 'manufacture', 'manuscript', 'manage', 'manipulate', 'emancipate'] },
  { root: 'oc / ocul', lang: 'Latin', gloss: 'eye', english: ['ocular', 'binoculars', 'monocle', 'oculist'] },
  { root: 'dent', lang: 'Latin', gloss: 'tooth', english: ['dentist', 'dental', 'denture', 'indent', 'trident'] },
  { root: 'digit', lang: 'Latin', gloss: 'finger, toe', english: ['digit', 'digital', 'prestidigitation'] },

  // ── Latin: qualities / prefixes / nouns ──────────────────────────
  { root: 'bene', lang: 'Latin', gloss: 'well, good', english: ['benefit', 'benevolent', 'benefactor', 'benign', 'benediction'] },
  { root: 'mal', lang: 'Latin', gloss: 'bad, ill', english: ['malice', 'malignant', 'malady', 'malfunction', 'malevolent', 'dismal'] },
  { root: 'magn', lang: 'Latin', gloss: 'great, large', english: ['magnify', 'magnitude', 'magnificent', 'magnate', 'magnanimous'] },
  { root: 'omni', lang: 'Latin', gloss: 'all', english: ['omnivore', 'omnipotent', 'omniscient', 'omnipresent'] },
  { root: 'multi', lang: 'Latin', gloss: 'many', english: ['multiple', 'multitude', 'multiply', 'multimedia'] },
  { root: 'vor', lang: 'Latin', gloss: 'to devour', english: ['carnivore', 'herbivore', 'voracious', 'devour', 'omnivore'] },
  { root: 'nov', lang: 'Latin', gloss: 'new', english: ['novel', 'novice', 'innovate', 'renovate', 'nova'] },
  { root: 'ver / verit', lang: 'Latin', gloss: 'true', english: ['verify', 'verdict', 'veracity', 'verity', 'aver'] },
  { root: 'sol', lang: 'Latin', gloss: 'sun', english: ['solar', 'solstice', 'parasol', 'solarium'] },
  { root: 'luc / lumin', lang: 'Latin', gloss: 'light', english: ['lucid', 'translucent', 'elucidate', 'illuminate', 'luminous', 'luminary'] },
  { root: 'nox / noc / nect', lang: 'Latin', gloss: 'night', english: ['nocturnal', 'equinox', 'nocturne'] },
  { root: 'aqua', lang: 'Latin', gloss: 'water', english: ['aquarium', 'aquatic', 'aqueduct', 'aquamarine'] },
  { root: 'mar / mari', lang: 'Latin', gloss: 'sea', english: ['marine', 'maritime', 'submarine', 'mariner', 'aquamarine'] },
  { root: 'terra', lang: 'Latin', gloss: 'earth, land', english: ['terrain', 'territory', 'terrestrial', 'subterranean', 'terrace', 'inter'] },
  { root: 'ign', lang: 'Latin', gloss: 'fire', english: ['ignite', 'ignition', 'igneous'] },
  { root: 'ventus', lang: 'Latin', gloss: 'wind', english: ['ventilate', 'vent', 'hyperventilate'] },
  { root: 'annus / enn', lang: 'Latin', gloss: 'year', english: ['annual', 'anniversary', 'biennial', 'perennial', 'annals', 'millennium'] },
  { root: 'tempus / tempor', lang: 'Latin', gloss: 'time', english: ['temporary', 'contemporary', 'temporal', 'tempo', 'extemporaneous'] },
  { root: 'greg', lang: 'Latin', gloss: 'flock, herd', english: ['gregarious', 'congregate', 'segregate', 'aggregate', 'egregious'] },
  { root: 'urb', lang: 'Latin', gloss: 'city', english: ['urban', 'suburb', 'urbane', 'exurb'] },
  { root: 'civ', lang: 'Latin', gloss: 'citizen', english: ['civil', 'civic', 'civilian', 'civilization'] },
  { root: 'jud / jur / jus', lang: 'Latin', gloss: 'law, to judge, to swear', english: ['judge', 'jury', 'justice', 'perjury', 'jurisdiction', 'prejudice'] },
  { root: 'leg / legis', lang: 'Latin', gloss: 'law', english: ['legal', 'legislate', 'legitimate', 'privilege', 'delegate'] },
  { root: 'pac / peac', lang: 'Latin', gloss: 'peace', english: ['pacify', 'pacific', 'appease', 'pact'] },
  { root: 'bell', lang: 'Latin', gloss: 'war', english: ['rebel', 'belligerent', 'bellicose', 'antebellum'] },
  { root: 'fid / fed', lang: 'Latin', gloss: 'faith, trust', english: ['fidelity', 'confide', 'federal', 'infidel', 'bona fide', 'perfidy'] },
  { root: 'cred', lang: 'Latin', gloss: 'to believe, trust', english: ['credit', 'credible', 'incredible', 'credential', 'creed', 'credulous'] },
  { root: 'am / amic', lang: 'Latin', gloss: 'love, friend', english: ['amiable', 'amity', 'amateur', 'enamored', 'amorous', 'amicable'] },
  { root: 'sanct', lang: 'Latin', gloss: 'holy', english: ['sanctuary', 'sanctify', 'sacrosanct', 'sanction'] },
  { root: 'sci', lang: 'Latin', gloss: 'to know', english: ['science', 'conscious', 'omniscient', 'prescient', 'conscience'] },
  { root: 'cogn / gnos', lang: 'Latin', gloss: 'to know', english: ['recognize', 'cognitive', 'incognito', 'cognizant'] },
  { root: 'doc / doct', lang: 'Latin', gloss: 'to teach', english: ['doctor', 'doctrine', 'document', 'indoctrinate', 'docile'] },
  { root: 'pot', lang: 'Latin', gloss: 'power, able', english: ['potent', 'potential', 'omnipotent', 'impotent', 'potentate'] },
  { root: 'val / vail', lang: 'Latin', gloss: 'to be strong, worth', english: ['valid', 'value', 'evaluate', 'prevail', 'valiant', 'equivalent'] },
  { root: 'grav', lang: 'Latin', gloss: 'heavy, serious', english: ['gravity', 'grave', 'aggravate', 'grievance'] },
  { root: 'lev', lang: 'Latin', gloss: 'light, to lift', english: ['elevate', 'lever', 'relieve', 'alleviate', 'levity'] },
  { root: 'brev', lang: 'Latin', gloss: 'short', english: ['brief', 'abbreviate', 'brevity', 'abridge'] },
  { root: 'long', lang: 'Latin', gloss: 'long', english: ['elongate', 'longitude', 'prolong', 'oblong'] },
  { root: 'aequ', lang: 'Latin', gloss: 'equal, even', english: ['equal', 'equator', 'adequate', 'equilibrium', 'equity'] },
  { root: 'liber', lang: 'Latin', gloss: 'free', english: ['liberty', 'liberate', 'liberal', 'deliver'] },
  { root: 'prim', lang: 'Latin', gloss: 'first', english: ['primary', 'prime', 'primitive', 'primeval', 'primate'] },
  { root: 'ultim', lang: 'Latin', gloss: 'last, farthest', english: ['ultimate', 'ultimatum', 'penultimate'] },
  { root: 'medi', lang: 'Latin', gloss: 'middle', english: ['medium', 'mediate', 'medieval', 'intermediate', 'median'] },

  // ── Greek ─────────────────────────────────────────────────────────
  { root: 'anthrop', lang: 'Greek', gloss: 'human, man', english: ['anthropology', 'philanthropy', 'misanthrope', 'anthropomorphic'] },
  { root: 'bio', lang: 'Greek', gloss: 'life', english: ['biology', 'biography', 'antibiotic', 'symbiosis', 'biosphere', 'amphibian'] },
  { root: 'zo', lang: 'Greek', gloss: 'animal, living being', english: ['zoo', 'zoology', 'protozoa', 'zodiac'] },
  { root: 'chron', lang: 'Greek', gloss: 'time', english: ['chronology', 'chronic', 'synchronize', 'anachronism', 'chronicle', 'chronometer'] },
  { root: 'phil', lang: 'Greek', gloss: 'love, fondness', english: ['philosophy', 'philanthropy', 'bibliophile', 'philharmonic', 'Anglophile'] },
  { root: 'mis / miso', lang: 'Greek', gloss: 'hatred', english: ['misanthrope', 'misogyny', 'misandry'] },
  { root: 'phon', lang: 'Greek', gloss: 'sound, voice', english: ['telephone', 'symphony', 'phonetic', 'cacophony', 'megaphone', 'homophone'] },
  { root: 'graph / gram', lang: 'Greek', gloss: 'writing, drawing, recording', english: ['photograph', 'grammar', 'diagram', 'telegram', 'biography', 'graphic', 'monogram'] },
  { root: 'log / logos', lang: 'Greek', gloss: 'word, reason, study', english: ['logic', 'dialogue', 'monologue', 'biology', 'analogy', 'catalogue', 'eulogy'] },
  { root: 'geo', lang: 'Greek', gloss: 'earth', english: ['geography', 'geology', 'geometry', 'geopolitics', 'geode'] },
  { root: 'hydr', lang: 'Greek', gloss: 'water', english: ['hydrant', 'dehydrate', 'hydraulic', 'hydrogen', 'hydroplane', 'hydrophobia'] },
  { root: 'pyr', lang: 'Greek', gloss: 'fire', english: ['pyre', 'pyromaniac', 'pyrotechnics', 'pyre'] },
  { root: 'aer', lang: 'Greek', gloss: 'air', english: ['aerial', 'aerobic', 'aerosol', 'aeronautics'] },
  { root: 'astr / aster', lang: 'Greek', gloss: 'star', english: ['astronomy', 'asterisk', 'disaster', 'astronaut', 'asteroid'] },
  { root: 'cosm', lang: 'Greek', gloss: 'universe, order', english: ['cosmos', 'cosmic', 'cosmopolitan', 'microcosm', 'cosmetic'] },
  { root: 'therm', lang: 'Greek', gloss: 'heat', english: ['thermometer', 'thermal', 'thermostat', 'hypothermia'] },
  { root: 'photo / phos', lang: 'Greek', gloss: 'light', english: ['photograph', 'photon', 'photosynthesis', 'phosphorus'] },
  { root: 'path', lang: 'Greek', gloss: 'feeling, suffering, disease', english: ['sympathy', 'empathy', 'pathology', 'apathy', 'pathetic', 'telepathy'] },
  { root: 'psych', lang: 'Greek', gloss: 'mind, soul', english: ['psychology', 'psyche', 'psychic', 'psychiatry'] },
  { root: 'nom / nomos', lang: 'Greek', gloss: 'law, custom', english: ['autonomy', 'economy', 'astronomy', 'taxonomy', 'antinomy'] },
  { root: 'poli / polis', lang: 'Greek', gloss: 'city', english: ['politics', 'metropolis', 'police', 'cosmopolitan', 'acropolis', 'megalopolis'] },
  { root: 'dem / demos', lang: 'Greek', gloss: 'people', english: ['democracy', 'demographic', 'epidemic', 'endemic', 'demagogue', 'pandemic'] },
  { root: 'kratos / cracy', lang: 'Greek', gloss: 'power, rule', english: ['democracy', 'aristocracy', 'autocracy', 'bureaucracy', 'theocracy', 'plutocracy'] },
  { root: 'arch / archi', lang: 'Greek', gloss: 'chief, rule, first', english: ['monarch', 'anarchy', 'architect', 'archangel', 'oligarchy', 'archetype'] },
  { root: 'auto', lang: 'Greek', gloss: 'self', english: ['automatic', 'autonomy', 'autograph', 'autobiography', 'automobile'] },
  { root: 'hetero', lang: 'Greek', gloss: 'other, different', english: ['heterogeneous', 'heterodox', 'heterosexual'] },
  { root: 'homo / homeo', lang: 'Greek', gloss: 'same', english: ['homogeneous', 'homonym', 'homophone', 'homeostasis'] },
  { root: 'mono', lang: 'Greek', gloss: 'one, single', english: ['monopoly', 'monotone', 'monologue', 'monarch', 'monolith'] },
  { root: 'poly', lang: 'Greek', gloss: 'many', english: ['polygon', 'polyglot', 'polygamy', 'polytheism', 'polymer'] },
  { root: 'micro', lang: 'Greek', gloss: 'small', english: ['microscope', 'microphone', 'microbe', 'microcosm'] },
  { root: 'macro', lang: 'Greek', gloss: 'large, long', english: ['macrocosm', 'macroeconomics', 'macron'] },
  { root: 'mega / megal', lang: 'Greek', gloss: 'great, large', english: ['megaphone', 'megabyte', 'megalomania', 'megalith'] },
  { root: 'pan / panto', lang: 'Greek', gloss: 'all', english: ['panorama', 'pandemic', 'pantheon', 'panacea', 'pandemonium'] },
  { root: 'proto', lang: 'Greek', gloss: 'first', english: ['prototype', 'protocol', 'protagonist', 'protozoa', 'proton'] },
  { root: 'tele', lang: 'Greek', gloss: 'far, distant', english: ['telephone', 'television', 'telescope', 'telepathy', 'telegram'] },
  { root: 'scop', lang: 'Greek', gloss: 'to look at, examine', english: ['telescope', 'microscope', 'periscope', 'stethoscope', 'kaleidoscope'] },
  { root: 'meter / metr', lang: 'Greek', gloss: 'measure', english: ['thermometer', 'diameter', 'perimeter', 'symmetry', 'geometry', 'barometer'] },
  { root: 'gen / genesis', lang: 'Greek', gloss: 'birth, origin, kind', english: ['genesis', 'genetic', 'genre', 'gene', 'pathogen', 'homogeneous'] },
  { root: 'morph', lang: 'Greek', gloss: 'form, shape', english: ['morphology', 'metamorphosis', 'amorphous', 'anthropomorphic', 'polymorphous'] },
  { root: 'onym / onoma', lang: 'Greek', gloss: 'name', english: ['synonym', 'antonym', 'pseudonym', 'anonymous', 'onomatopoeia', 'acronym'] },
  { root: 'phor / pher', lang: 'Greek', gloss: 'to carry, bear', english: ['metaphor', 'euphoria', 'pheromone', 'semaphore', 'phosphorus'] },
  { root: 'crit / cris', lang: 'Greek', gloss: 'to judge, separate', english: ['critic', 'criterion', 'crisis', 'hypocrite', 'diacritic'] },
  { root: 'dox / doc', lang: 'Greek', gloss: 'opinion, belief, glory', english: ['orthodox', 'paradox', 'doctrine', 'doxology', 'heterodox'] },
  { root: 'gno / gnos', lang: 'Greek', gloss: 'to know', english: ['diagnosis', 'prognosis', 'agnostic', 'gnostic'] },
  { root: 'phag', lang: 'Greek', gloss: 'to eat', english: ['esophagus', 'sarcophagus', 'bacteriophage', 'anthropophagy'] },
  { root: 'derm', lang: 'Greek', gloss: 'skin', english: ['dermatology', 'epidermis', 'hypodermic', 'pachyderm', 'taxidermy'] },
  { root: 'cardi', lang: 'Greek', gloss: 'heart', english: ['cardiac', 'cardiology', 'electrocardiogram', 'tachycardia'] },
  { root: 'neur', lang: 'Greek', gloss: 'nerve', english: ['neuron', 'neurology', 'neurotic', 'neuralgia'] },
  { root: 'hema / hemo', lang: 'Greek', gloss: 'blood', english: ['hemoglobin', 'hemorrhage', 'hemophilia', 'anemia'] },
  { root: 'gastr', lang: 'Greek', gloss: 'stomach', english: ['gastric', 'gastronomy', 'gastritis', 'gastropod'] },
  { root: 'pod / pous', lang: 'Greek', gloss: 'foot', english: ['podium', 'tripod', 'podiatrist', 'antipodes', 'octopus'] },
  { root: 'cheir / chiro', lang: 'Greek', gloss: 'hand', english: ['chiropractor', 'chiropody', 'chirography'] },
  { root: 'ortho', lang: 'Greek', gloss: 'straight, correct', english: ['orthodox', 'orthopedic', 'orthography', 'orthodontist'] },
  { root: 'iso', lang: 'Greek', gloss: 'equal', english: ['isolate', 'isosceles', 'isotope', 'isobar'] },
  { root: 'hyper', lang: 'Greek', gloss: 'over, above, excessive', english: ['hyperbole', 'hyperactive', 'hypertension', 'hyperlink'] },
  { root: 'hypo', lang: 'Greek', gloss: 'under, below', english: ['hypodermic', 'hypothesis', 'hypothermia', 'hypocrite'] },
  { root: 'peri', lang: 'Greek', gloss: 'around', english: ['perimeter', 'periscope', 'periphery', 'pericardium'] },
  { root: 'syn / sym', lang: 'Greek', gloss: 'with, together', english: ['synonym', 'synthesis', 'symphony', 'sympathy', 'synchronize', 'symbiosis'] },
  { root: 'dia', lang: 'Greek', gloss: 'through, across', english: ['diameter', 'dialogue', 'diagnosis', 'diagonal', 'diaphragm'] },
  { root: 'ana', lang: 'Greek', gloss: 'up, back, again', english: ['analysis', 'anatomy', 'anachronism', 'analogy'] },
  { root: 'cata', lang: 'Greek', gloss: 'down, against', english: ['catastrophe', 'catalogue', 'catapult', 'cataract'] },
  { root: 'epi', lang: 'Greek', gloss: 'on, upon, over', english: ['epidermis', 'epidemic', 'epilogue', 'epitaph', 'epicenter'] },
  { root: 'ec / ex / exo', lang: 'Greek', gloss: 'out, outside', english: ['exodus', 'exorcism', 'eccentric', 'ecstasy', 'exotic'] },
  { root: 'eu', lang: 'Greek', gloss: 'good, well', english: ['euphoria', 'euphemism', 'eulogy', 'euthanasia', 'euphonic'] },
  { root: 'dys', lang: 'Greek', gloss: 'bad, difficult, abnormal', english: ['dysfunction', 'dyslexia', 'dystopia', 'dyspepsia'] },
  { root: 'a / an', lang: 'Greek', gloss: 'not, without', english: ['atheist', 'anarchy', 'apathy', 'anonymous', 'amoral', 'asymmetric'] },
  { root: 'neo', lang: 'Greek', gloss: 'new', english: ['neon', 'neophyte', 'neolithic', 'neonatal'] },
  { root: 'paleo', lang: 'Greek', gloss: 'old, ancient', english: ['paleontology', 'paleolithic', 'paleography'] },
  { root: 'phob', lang: 'Greek', gloss: 'fear', english: ['phobia', 'claustrophobia', 'xenophobia', 'hydrophobia'] },
  { root: 'mania', lang: 'Greek', gloss: 'madness, obsession', english: ['maniac', 'kleptomania', 'pyromania', 'megalomania'] },
  { root: 'techn', lang: 'Greek', gloss: 'art, skill, craft', english: ['technology', 'technique', 'technical', 'pyrotechnics', 'polytechnic'] },
  { root: 'soph', lang: 'Greek', gloss: 'wisdom', english: ['philosophy', 'sophisticated', 'sophomore', 'sophistry'] },
  { root: 'the / theo', lang: 'Greek', gloss: 'god', english: ['theology', 'atheist', 'polytheism', 'monotheism', 'pantheon'] },
  { root: 'hier', lang: 'Greek', gloss: 'sacred', english: ['hierarchy', 'hieroglyphics', 'hierophant'] },
  { root: 'bibl', lang: 'Greek', gloss: 'book', english: ['bibliography', 'bible', 'bibliophile', 'bibliomania'] },
  { root: 'phys', lang: 'Greek', gloss: 'nature', english: ['physics', 'physical', 'physiology', 'metaphysics'] },
  { root: 'chrom', lang: 'Greek', gloss: 'color', english: ['chromosome', 'monochrome', 'chromatic', 'chrome'] },
  { root: 'kine / cine', lang: 'Greek', gloss: 'movement', english: ['kinetic', 'cinema', 'kinesthetic', 'telekinesis'] },
  { root: 'dyna / dynam', lang: 'Greek', gloss: 'power', english: ['dynamic', 'dynamite', 'dynamo', 'dynasty'] },
  { root: 'therap', lang: 'Greek', gloss: 'healing, treatment', english: ['therapy', 'therapist', 'chemotherapy'] },
  { root: 'lith', lang: 'Greek', gloss: 'stone', english: ['monolith', 'lithography', 'megalith', 'neolithic'] },
  { root: 'hydro', lang: 'Greek', gloss: 'water', english: ['hydrofoil', 'hydroelectric', 'carbohydrate'] },
  { root: 'agon', lang: 'Greek', gloss: 'struggle, contest', english: ['agony', 'protagonist', 'antagonist', 'agonize'] },
  { root: 'chrys', lang: 'Greek', gloss: 'gold', english: ['chrysalis', 'chrysanthemum'] },
  { root: 'helio', lang: 'Greek', gloss: 'sun', english: ['heliocentric', 'helium', 'heliotrope'] },
  { root: 'sema / semant', lang: 'Greek', gloss: 'sign, meaning', english: ['semantics', 'semaphore', 'semiotics'] },
  { root: 'taxis / tax', lang: 'Greek', gloss: 'arrangement, order', english: ['taxonomy', 'syntax', 'taxidermy'] },
];
